using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Straddle.Core;
using Straddle.Exceptions;

namespace Straddle.Models.Bridge.Link;

/// <summary>
/// Creates a new paykey using a Quiltt token as the source. This endpoint allows
/// you to create a secure payment token linked to a bank account authenticated through Quiltt.
///
/// <para>NOTE: Do not inherit from this type outside the SDK unless you're okay with
/// breaking changes in non-major versions. We may add new methods in the future that
/// cause existing derived classes to break.</para>
/// </summary>
public record class LinkCreatePaykeyParams : ParamsBase
{
    readonly JsonDictionary _rawBodyData = new();
    public IReadOnlyDictionary<string, JsonElement> RawBodyData
    {
        get { return this._rawBodyData.Freeze(); }
    }

    /// <summary>
    /// Unique identifier of the related customer object.
    /// </summary>
    public required string CustomerID
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNotNullClass<string>("customer_id");
        }
        init { this._rawBodyData.Set("customer_id", value); }
    }

    /// <summary>
    /// Quiltt processor token generated by your application for use with the Straddle API.
    /// </summary>
    public required string QuilttToken
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNotNullClass<string>("quiltt_token");
        }
        init { this._rawBodyData.Set("quiltt_token", value); }
    }

    public LinkCreatePaykeyParamsConfig? Config
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<LinkCreatePaykeyParamsConfig>("config");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawBodyData.Set("config", value);
        }
    }

    /// <summary>
    /// Unique identifier for the paykey in your database, used for cross-referencing
    /// between Straddle and your systems.
    /// </summary>
    public string? ExternalID
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<string>("external_id");
        }
        init { this._rawBodyData.Set("external_id", value); }
    }

    /// <summary>
    /// Up to 20 additional user-defined key-value pairs. Useful for storing additional
    /// information about the paykey in a structured format.
    /// </summary>
    public IReadOnlyDictionary<string, string>? Metadata
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<FrozenDictionary<string, string>>("metadata");
        }
        init
        {
            this._rawBodyData.Set<FrozenDictionary<string, string>?>(
                "metadata",
                value == null ? null : FrozenDictionary.ToFrozenDictionary(value)
            );
        }
    }

    public string? CorrelationID
    {
        get
        {
            this._rawHeaderData.Freeze();
            return this._rawHeaderData.GetNullableClass<string>("Correlation-Id");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawHeaderData.Set("Correlation-Id", value);
        }
    }

    public string? IdempotencyKey
    {
        get
        {
            this._rawHeaderData.Freeze();
            return this._rawHeaderData.GetNullableClass<string>("Idempotency-Key");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawHeaderData.Set("Idempotency-Key", value);
        }
    }

    public string? RequestID
    {
        get
        {
            this._rawHeaderData.Freeze();
            return this._rawHeaderData.GetNullableClass<string>("Request-Id");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawHeaderData.Set("Request-Id", value);
        }
    }

    public string? StraddleAccountID
    {
        get
        {
            this._rawHeaderData.Freeze();
            return this._rawHeaderData.GetNullableClass<string>("Straddle-Account-Id");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawHeaderData.Set("Straddle-Account-Id", value);
        }
    }

    public LinkCreatePaykeyParams() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public LinkCreatePaykeyParams(LinkCreatePaykeyParams linkCreatePaykeyParams)
        : base(linkCreatePaykeyParams)
    {
        this._rawBodyData = new(linkCreatePaykeyParams._rawBodyData);
    }
#pragma warning restore CS8618

    public LinkCreatePaykeyParams(
        IReadOnlyDictionary<string, JsonElement> rawHeaderData,
        IReadOnlyDictionary<string, JsonElement> rawQueryData,
        IReadOnlyDictionary<string, JsonElement> rawBodyData
    )
    {
        this._rawHeaderData = new(rawHeaderData);
        this._rawQueryData = new(rawQueryData);
        this._rawBodyData = new(rawBodyData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    LinkCreatePaykeyParams(
        FrozenDictionary<string, JsonElement> rawHeaderData,
        FrozenDictionary<string, JsonElement> rawQueryData,
        FrozenDictionary<string, JsonElement> rawBodyData
    )
    {
        this._rawHeaderData = new(rawHeaderData);
        this._rawQueryData = new(rawQueryData);
        this._rawBodyData = new(rawBodyData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="IFromRawJson.FromRawUnchecked"/>
    public static LinkCreatePaykeyParams FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawHeaderData,
        IReadOnlyDictionary<string, JsonElement> rawQueryData,
        IReadOnlyDictionary<string, JsonElement> rawBodyData
    )
    {
        return new(
            FrozenDictionary.ToFrozenDictionary(rawHeaderData),
            FrozenDictionary.ToFrozenDictionary(rawQueryData),
            FrozenDictionary.ToFrozenDictionary(rawBodyData)
        );
    }

    public override string ToString() =>
        JsonSerializer.Serialize(
            new Dictionary<string, object?>()
            {
                ["HeaderData"] = this._rawHeaderData.Freeze(),
                ["QueryData"] = this._rawQueryData.Freeze(),
                ["BodyData"] = this._rawBodyData.Freeze(),
            },
            ModelBase.ToStringSerializerOptions
        );

    public virtual bool Equals(LinkCreatePaykeyParams? other)
    {
        if (other == null)
        {
            return false;
        }
        return this._rawHeaderData.Equals(other._rawHeaderData)
            && this._rawQueryData.Equals(other._rawQueryData)
            && this._rawBodyData.Equals(other._rawBodyData);
    }

    public override Uri Url(ClientOptions options)
    {
        return new UriBuilder(options.BaseUrl.ToString().TrimEnd('/') + "/v1/bridge/quiltt")
        {
            Query = this.QueryString(options),
        }.Uri;
    }

    internal override HttpContent? BodyContent()
    {
        return new StringContent(
            JsonSerializer.Serialize(this.RawBodyData, ModelBase.SerializerOptions),
            Encoding.UTF8,
            "application/json"
        );
    }

    internal override void AddHeadersToRequest(HttpRequestMessage request, ClientOptions options)
    {
        ParamsBase.AddDefaultHeaders(request, options);
        foreach (var item in this.RawHeaderData)
        {
            ParamsBase.AddHeaderElementToRequest(request, item.Key, item.Value);
        }
    }

    public override int GetHashCode()
    {
        return 0;
    }
}

[JsonConverter(
    typeof(JsonModelConverter<LinkCreatePaykeyParamsConfig, LinkCreatePaykeyParamsConfigFromRaw>)
)]
public sealed record class LinkCreatePaykeyParamsConfig : JsonModel
{
    public ApiEnum<string, LinkCreatePaykeyParamsConfigProcessingMethod>? ProcessingMethod
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<
                ApiEnum<string, LinkCreatePaykeyParamsConfigProcessingMethod>
            >("processing_method");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("processing_method", value);
        }
    }

    public ApiEnum<string, LinkCreatePaykeyParamsConfigSandboxOutcome>? SandboxOutcome
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<
                ApiEnum<string, LinkCreatePaykeyParamsConfigSandboxOutcome>
            >("sandbox_outcome");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("sandbox_outcome", value);
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        this.ProcessingMethod?.Validate();
        this.SandboxOutcome?.Validate();
    }

    public LinkCreatePaykeyParamsConfig() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public LinkCreatePaykeyParamsConfig(LinkCreatePaykeyParamsConfig linkCreatePaykeyParamsConfig)
        : base(linkCreatePaykeyParamsConfig) { }
#pragma warning restore CS8618

    public LinkCreatePaykeyParamsConfig(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    LinkCreatePaykeyParamsConfig(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="LinkCreatePaykeyParamsConfigFromRaw.FromRawUnchecked"/>
    public static LinkCreatePaykeyParamsConfig FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class LinkCreatePaykeyParamsConfigFromRaw : IFromRawJson<LinkCreatePaykeyParamsConfig>
{
    /// <inheritdoc/>
    public LinkCreatePaykeyParamsConfig FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => LinkCreatePaykeyParamsConfig.FromRawUnchecked(rawData);
}

[JsonConverter(typeof(LinkCreatePaykeyParamsConfigProcessingMethodConverter))]
public enum LinkCreatePaykeyParamsConfigProcessingMethod
{
    Inline,
    Background,
    Skip,
}

sealed class LinkCreatePaykeyParamsConfigProcessingMethodConverter
    : JsonConverter<LinkCreatePaykeyParamsConfigProcessingMethod>
{
    public override LinkCreatePaykeyParamsConfigProcessingMethod Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "inline" => LinkCreatePaykeyParamsConfigProcessingMethod.Inline,
            "background" => LinkCreatePaykeyParamsConfigProcessingMethod.Background,
            "skip" => LinkCreatePaykeyParamsConfigProcessingMethod.Skip,
            _ => (LinkCreatePaykeyParamsConfigProcessingMethod)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        LinkCreatePaykeyParamsConfigProcessingMethod value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                LinkCreatePaykeyParamsConfigProcessingMethod.Inline => "inline",
                LinkCreatePaykeyParamsConfigProcessingMethod.Background => "background",
                LinkCreatePaykeyParamsConfigProcessingMethod.Skip => "skip",
                _ => throw new StraddleInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}

[JsonConverter(typeof(LinkCreatePaykeyParamsConfigSandboxOutcomeConverter))]
public enum LinkCreatePaykeyParamsConfigSandboxOutcome
{
    Standard,
    Active,
    Rejected,
    Review,
}

sealed class LinkCreatePaykeyParamsConfigSandboxOutcomeConverter
    : JsonConverter<LinkCreatePaykeyParamsConfigSandboxOutcome>
{
    public override LinkCreatePaykeyParamsConfigSandboxOutcome Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "standard" => LinkCreatePaykeyParamsConfigSandboxOutcome.Standard,
            "active" => LinkCreatePaykeyParamsConfigSandboxOutcome.Active,
            "rejected" => LinkCreatePaykeyParamsConfigSandboxOutcome.Rejected,
            "review" => LinkCreatePaykeyParamsConfigSandboxOutcome.Review,
            _ => (LinkCreatePaykeyParamsConfigSandboxOutcome)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        LinkCreatePaykeyParamsConfigSandboxOutcome value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                LinkCreatePaykeyParamsConfigSandboxOutcome.Standard => "standard",
                LinkCreatePaykeyParamsConfigSandboxOutcome.Active => "active",
                LinkCreatePaykeyParamsConfigSandboxOutcome.Rejected => "rejected",
                LinkCreatePaykeyParamsConfigSandboxOutcome.Review => "review",
                _ => throw new StraddleInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}
